### ISSUE TITLE
ftd2xx.dll issues

### ISSUE THREAD

**Issue by ciozi137** [levylabpitt/Relay-Box#1]
![image](https://user-images.githubusercontent.com/26659428/171495170-1b816422-c1e3-45c2-9291-4641a677a6f1.png)
linking? bitness?

**Comment by ciozi137** [comment]
I think if the dll (and VIs) are held inside a lvlib or lvclass there should be less issues with the CLFNs finding the dll. I'm running Dependency Walker now to see if there are other issues or missing dependencies

**Comment by Monkeymerlot** [comment]
OK. I did not make this package so I know really little about it in general. It was giving me a _lot_ of conflicts when I switched to 2019...

**Comment by ciozi137** [comment]
This isn't the first time I've had problems with this file. This task is to fix the problem once and for all

**Comment by ciozi137** [comment]
This project was a real mess. I downloaded fresh copies of the LV drivers and dlls directly from FTDI. I fixed all of the linking and now I'm building a new package.
